<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class ChargesCreateMultiIndex extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('business_charges', function (Blueprint $table) {
          $table->index([
            'channel', 
            'status', 
            'plugin_provider', 
            'is_successful_plugin_callback', 
            'callback_url_retry_count'
          ], 'find_charges_index'); // autogenerated name is too long
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
      Schema::table('business_charges', function (Blueprint $table) {
        $table->dropIndex('find_charges_index');
      });        
    }
}
